name: Check Version

on:
  pull_request:
    branches:
      - master

jobs:
  check-version:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Get project version
        run: |
          VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')
          echo "::set-env name=VERSION::$VERSION"
      - name: Check version
        if: endsWith(env.VERSION, '-SNAPSHOT') == false
        run: if git rev-parse v$VERSION >/dev/null 2>&1; then exit 1; fi
